<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="connect_offset" value="0.02633"/>
    <xacro:property name="thigh_offset_y" value="-0.0645"/>
    <xacro:property name="thigh_offset_z" value="-0.0145"/>

    <xacro:property name="lenght_lidar" value="0.04" />
    <xacro:property name="radius_lidar" value="0.03" />
    <xacro:property name="mass_lidar" value="0.1" />

    <xacro:macro name="phantomx" params="parent *origin">


        <joint name="j_phantomx_attachment" type="fixed">
            <parent link="${parent}"/>
            <child link="MP_BODY"/>
            <insert_block name="origin"/>
        </joint>

<!-- ############# Link ####################### -->

        <link name="MP_BODY">
            <inertial>
                <origin xyz="0 0 0"/>
                <mass value="0.97559947"/>
                <inertia ixx="3.1081800" ixy="-0.25460189" ixz="2.0318174" iyy="6.3787776" iyz="0.16417863"
                         izz="5.3316425"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/body.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/body_coll.STL" scale="1 1 1"/>
                </geometry>

            </collision>
        </link>

        <gazebo reference="MP_BODY">
            <material>Gazebo/YellowGlow</material>
        </gazebo>

        <xacro:leg_l xyz="0.1248 -0.06164  0.001116" rpy="0 4.7123 0.7853981633974483" suffix="rf"/>
        <xacro:leg_l xyz="0 -0.1034  0.001116" rpy="0 4.7123 0" suffix="rm"/>
        <xacro:leg_l xyz="-0.1248 -0.06164  0.001116" rpy="0 4.7123 -0.7853981633974483" suffix="rr"/>


        <xacro:leg_l xyz="0.1248 0.06164  0.001116" rpy="0 4.7123 2.356194490192345" suffix="lf"/>
        <xacro:leg_l xyz="0 0.1034  0.001116" rpy="0 4.7123 3.14159" suffix="lm"/>
        <xacro:leg_l xyz="-0.1248 0.06164  0.001116" rpy="0 4.7123 3.9269908169872414" suffix="lr"/>

    </xacro:macro>

    <xacro:macro name="leg_l" params="xyz rpy suffix">



        <link name="c1_${suffix}">
            <inertial>
                <origin xyz="0 -${connect_offset} 0" rpy="0 0 0"/>
                <mass value="0.324357719"/>
                <inertia ixx="0.0051411124" ixy="-0.00057530255" ixz="-0.000024729049" iyy="0.0081915737"
                         iyz="-0.000019223094" izz="0.0011379812"/>
            </inertial>
            <visual>
                <origin xyz="0 -0.0252 0" rpy="0 0 0"/>
                <geometry>
                    <!--box size="0.045 0.022 0.0325" /-->
                    <mesh filename="package://phantomx_description/meshes/connect.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 -${connect_offset} 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/connect_coll.STL" scale="1 1 1"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="c1_${suffix}">
            <dampingFactor>0.0005</dampingFactor>
        </gazebo>

        <link name="c2_${suffix}">
            <inertial>
                <origin xyz="0 -${connect_offset} 0" rpy="0 0 0"/>
                <mass value="0.324357719"/>
                <inertia ixx="0.0051411124" ixy="-0.00057530255" ixz="-0.000024729049" iyy="0.0081915737"
                         iyz="-0.000019223094" izz="0.0011379812"/>
            </inertial>
            <visual>
                <origin xyz="0 -0.0252 0" rpy="0 0 0"/>
                <geometry>
                    <!--box size="0.045 0.022 0.0325" /-->
                    <mesh filename="package://phantomx_description/meshes/connect.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 -${connect_offset} 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/connect_coll.STL" scale="1 1 1"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="c2_${suffix}">
            <dampingFactor>0.0005</dampingFactor>
        </gazebo>

        <link name="thigh_${suffix}">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.324357719"/>
                <inertia ixx="0.0051411124" ixy="-0.00057530255" ixz="-0.000024729049" iyy="0.0081915737"
                         iyz="-0.000019223094" izz="0.0011379812"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/thigh_l.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/thigh_l_coll.STL" scale="1 1 1"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="thigh_${suffix}">
            <dampingFactor>0.0005</dampingFactor>
        </gazebo>

        <link name="tibia_${suffix}">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.324357719"/>
                <inertia ixx="0.0051411124" ixy="-0.00057530255" ixz="-0.000024729049" iyy="0.0081915737"
                         iyz="-0.000019223094" izz="0.0011379812"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/tibia_l.STL" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://phantomx_description/meshes/tibia_l_coll.STL" scale="1 1 1"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="tibia_${suffix}">
            <mu1>50.0</mu1>
            <mu2>50.0</mu2>
            <fdir1>0.000000 0.000000 0.000000</fdir1>
            <kp>500000.0</kp>
            <kd>10.0</kd>
            <maxVel>0.00</maxVel>
            <minDepth>0.001</minDepth>
            <dampingFactor>0.0005</dampingFactor>
            <selfCollide>1</selfCollide>
        </gazebo>




<!-- ################## Joint #################### -->

        <joint name="j_c1_${suffix}" type="revolute">
            <parent link="MP_BODY"/>
            <child link="c1_${suffix}"/>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <axis xyz="1 0 0"/>
            <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939"/>
        </joint>

        <joint name="j_c2_${suffix}" type="fixed">
            <parent link="c1_${suffix}"/>
            <child link="c2_${suffix}"/>
            <origin xyz="0 -0.054 0" rpy="0 1.5704 3.14159"/>
        </joint>

        <joint name="j_thigh_${suffix}" type="revolute">
            <parent link="c2_${suffix}"/>
            <child link="thigh_${suffix}"/>
            <origin xyz="0 0 0" rpy=" 0 3.14159 3.14159"/>
            <axis xyz="1 0 0"/>
            <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939"/>
        </joint>

        <joint name="j_tibia_${suffix}" type="revolute">
            <parent link="thigh_${suffix}"/>
            <child link="tibia_${suffix}"/>
            <origin xyz="0 ${thigh_offset_y} ${thigh_offset_z}" rpy="-1.5707 0 3.14159"/>
            <axis xyz="1 0 0"/>
            <limit effort="2.8" velocity="5.6548668" lower="-2.6179939" upper="2.6179939"/>
        </joint>




<!-- ################### transmission ##################### -->


        <transmission name="t_c1_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="j_c1_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="m_c1_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="t_thigh_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="j_thigh_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="m_thigh_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <transmission name="t_tibia_${suffix}">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="j_tibia_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="m_tibia_${suffix}">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>


<!-- ###################### reference #################### -->

        <gazebo reference="c1_${suffix}">
            <material>Gazebo/RedGlow</material>
        </gazebo>

        <gazebo reference="c2_${suffix}">
            <material>Gazebo/GreenGlow</material>
        </gazebo>

        <gazebo reference="thigh_${suffix}">
            <material>Gazebo/TurquoiseGlow</material>
        </gazebo>

        <gazebo reference="tibia_${suffix}">
        	<material>Gazebo/PurpleGlow</material>
        </gazebo>

    </xacro:macro>

<!--  ###################  Lidar ###################### -->

<link name="lidar">
    <collision>
        <geometry>
            <cylinder length="${lenght_lidar}" radius="${radius_lidar}"/>
            <origin rpy="0 0 0" xyz="0 0 ${-lenght_lidar/2}}"/>
        </geometry>
    </collision>

    <visual>
        <geometry>
            <cylinder length="${lenght_lidar}" radius="${radius_lidar}"/>
            <origin rpy="0 0 0" xyz="0 0 ${-lenght_lidar/2}"/>
        </geometry>
        <material name="red"/>
    </visual>

    <inertial>
        <mass value="0"/>
        <inertia
            ixx="${mass_lidar*lenght_lidar*lenght_lidar/12.0+mass_lidar*radius_lidar*radius_lidar/2.0}" ixy="0.0" ixz="0.0"
            iyy="${mass_lidar*lenght_lidar*lenght_lidar/12.0+mass_lidar*radius_lidar*radius_lidar/2.0}" iyz="0.0"
            izz="${mass_lidar*radius_lidar*radius_lidar}"/>
    </inertial>

</link>

<joint name="lidar_joint" type="fixed">
    <parent link="MP_BODY"/>
    <child link="lidar"/>
    <origin rpy="0 0 0" xyz="0 0 ${0.045/2+lenght_lidar/2}"/>
</joint>


<gazebo reference="lidar">
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose> 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>5</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>lidar</frameName>
      </plugin>
    </sensor>
  </gazebo>


    <!-- ################################################################# -->
    <!-- ###    Camera  ################################################## -->
    <!-- ################################################################# -->

    <!-- Add camera object -->
    <link name="camera">
        <visual>
            <geometry>
                <box size="0.02 0.02 0.02" />
            </geometry>
        </visual>
    </link>

    <!-- Add wonderful color to camera -->
    <gazebo reference="camera">
        <material>Gazebo/BlueGlow</material>
    </gazebo>

    <!-- Add link between camera and body object -->
    <joint name="body2camera" type="fixed">
        <parent link="MP_BODY"/>
        <child link="camera"/>
        <origin rpy="0 0 0" xyz="0.11 0 0"/>
    </joint>

    <!-- Add camera description 
    <gazebo reference="camera">
        <sensor type="camera" name="camera1">
            <update_rate>30.0</update_rate>
            <camera name="head">
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>800</width>
                    <height>800</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.02</near>
                    <far>300</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>0.0</updateRate>
            <cameraName>rrbot/camera1</cameraName>
            <imageTopicName>image_raw</imageTopicName>
            <cameraInfoTopicName>camera_info</cameraInfoTopicName>
            <frameName>camera_link</frameName>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
            </plugin>
        </sensor>
    </gazebo> -->

    <gazebo reference="camera">
        <sensor name='camera1' type='depth'>
            <always_on>1</always_on>
            <visualize>1</visualize>
            <camera name='head'>
                <horizontal_fov>1.047</horizontal_fov>
                    <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <depth_camera>
                    <output>depths</output>
                </depth_camera>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <plugin name='camera_controller' filename='libgazebo_ros_openni_kinect.so'>
            <alwaysOn>true</alwaysOn>
            <updateRate>30.0</updateRate>
            <cameraName>camera</cameraName>
            <frameName>/camera_link</frameName>
            <imageTopicName>rgb/image_raw</imageTopicName>
            <depthImageTopicName>depth/image_raw</depthImageTopicName>
            <pointCloudTopicName>depth/points</pointCloudTopicName>
            <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
            <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
            <pointCloudCutoff>0.4</pointCloudCutoff>
            <hackBaseline>0.07</hackBaseline>
            <distortionK1>0.0</distortionK1>
            <distortionK2>0.0</distortionK2>
            <distortionK3>0.0</distortionK3>
            <distortionT1>0.0</distortionT1>
            <distortionT2>0.0</distortionT2>
            <CxPrime>0.0</CxPrime>
            <Cx>0.0</Cx>
            <Cy>0.0</Cy>
            <focalLength>0.0</focalLength>
            </plugin>
        </sensor>
    </gazebo>


</robot>
